<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="prashants-MacBook-Air.local" name="com.qa.rest.tests.GetCallBDD" tests="7" failures="0" timestamp="2021-04-14T15:36:30 IST" time="7.612" errors="1">
  <testcase name="getContentType" time="2.447" classname="com.qa.rest.tests.GetCallBDD"/>
  <system-out/>
  <testcase name="getResponseBody" time="1.309" classname="com.qa.rest.tests.GetCallBDD"/>
  <system-out/>
  <testcase name="getSpecificPartofResponse" time="0.851" classname="com.qa.rest.tests.GetCallBDD">
    <error type="java.lang.ClassCastException" message="io.restassured.path.xml.XmlPath cannot be cast to java.util.ArrayList">
      <![CDATA[java.lang.ClassCastException: io.restassured.path.xml.XmlPath cannot be cast to java.util.ArrayList
at com.qa.rest.tests.GetCallBDD.getSpecificPartofResponse(GetCallBDD.java:71)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(ArrayList.java:1257)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- getSpecificPartofResponse -->
  <system-out/>
  <testcase name="getResponseHeader" time="0.696" classname="com.qa.rest.tests.GetCallBDD"/>
  <system-out/>
  <testcase name="test_numberofCircuitsfor2017_Season" time="0.908" classname="com.qa.rest.tests.GetCallBDD"/>
  <system-out/>
  <testcase name="getResponseStatus" time="0.686" classname="com.qa.rest.tests.GetCallBDD"/>
  <system-out/>
  <testcase name="getResponseTime" time="0.715" classname="com.qa.rest.tests.GetCallBDD"/>
  <system-out/>
</testsuite> <!-- com.qa.rest.tests.GetCallBDD -->
